### ISSUE TITLE
Inject date

### ISSUE THREAD

**Issue by nfroidure** [lukechilds/expired#6]
Thank you for the library.

It would be nice if we could have a way to inject the currentTime on the call so that the module could be used as a pure function.

**Comment by lukechilds** [comment]
Yeah, that makes sense.

Stuck in immigration right now but should be able to get this done tonight.

**Comment by lukechilds** [comment]
@nfroidure Done!

https://github.com/lukechilds/expired#pure-usage

Thanks for the suggestion 👍
